# Configuration file for trinag model and hyperparameter settings
# of crop and weed dataset

# learning rate
# one of 'batch_norm' or 'sync_bn' or 'layer_norm'
norm_typ: 'batch_norm' # It evoked problem. when norm_typ was 'sync_bn' and model.eval(), All outputs got Zero values
BN_MOM: 0.9
SyncBN_MOM: 3e-4
# Hamburger Parameters
ham_channels: 512

DUAL: False
SPATIAL: False
RAND_INIT: False

MD_S: 1
MD_D: 512
MD_R: 64

TRAIN_STEPS: 6
EVAL_STEPS: 6

INV_T: 1
BETA: 0.1
Eta: 0.9